inherit_from: https://raw.githubusercontent.com/decidim/decidim/release/0.27-stable/.rubocop.yml

AllCops:
  Include:
    - "**/*.rb"
    - "**/*.rake"
    - "**/*.ru"
    - "**/Gemfile"
    - "**/Rakefile"
  Exclude:
    - "development_app/**/*"
    - "spec/decidim_dummy_app/**/*"
    - "bin/**/*"
    - "node_modules/**/*"
    - "db/schema.rb"
    - "vendor/**/*"

Metrics/CyclomaticComplexity:
  Exclude:
    - "app/commands/decidim/extra_user_fields/admin/update_extra_user_fields.rb"

Metrics/PerceivedComplexity:
  Exclude:
    - "app/commands/decidim/extra_user_fields/admin/update_extra_user_fields.rb"

RSpec/FilePath:
  Exclude:
    - "spec/serializers/user_export_serializer_spec.rb"
